---
name: Test & Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Python ${{ matrix.python-version }} tests
    runs-on: [self-hosted]
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13.0-alpha.1"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install .[test]
          python -m pip install pytest-github-actions-annotate-failures

      - name: pytest
        run: PYTHONHASHSEED=123345 python -m pytest -v tests

  release:
    name: Semantic Release
    runs-on: [self-hosted]
    concurrency: push
    needs: [test]
    if: github.repository == 'cemlyn007/apple-gpu'
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Python Semantic Release
        run: |
          python -m pip install python-semantic-release==8.1.2 twine==4.0.2
          git config --global user.name "$GIT_COMMITTER_NAME"
          git config --global user.email "$GIT_COMMITTER_EMAIL"
          git config --system --add safe.directory "*"
          python -m semantic_release --verbose version
          python -m semantic_release --verbose publish
          [ -d "dist" ] && python -m twine upload dist/* --disable-progress-bar --verbose
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_REPOSITORY: pypi
